name: Ejecutar Scraper de FBref Big5 Salaries

on:
  schedule:
    - cron: '0 8 5 2 *'   # 5 de febrero a las 08:00 UTC
    - cron: '0 8 10 10 *' # 10 de octubre a las 08:00 UTC
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas lxml html5lib unidecode

      - name: Ejecutar script de shooting
        run: python scripts/salaries_big5.py

      - name: Commit y Push del archivo CSV generado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Actualizar datos de shooting (CSV) [skip ci]"
          branch: main
          file_pattern: ./data/salaries.csv
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
