name: Scrape and commit teams stats other

on:
  schedule:
    - cron: '0 8 * * 3'         # Wednesday 08:00 UTC
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show versions
        run: |
          python -V
          google-chrome --version || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install selenium bs4 pandas

      - name: Run the script
        env:
          CI: "true"             
        run: |
          python scripts/teams_stats_other.py || (echo "Script failed, listing debug files"; ls -lah data || true; exit 1)

      - name: Upload CSV artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: teams_stats_other
          path: |
            data/teams_stats_other.csv
            data/season.csv
          if-no-files-found: warn

      - name: Commit and Push the generated CSV file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update teams_stats_other.csv"
          branch: main
          file_pattern: ./data/teams_stats_other.csv
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
