name: Scrape and commit teams stats other

on:
  schedule:
    # Every Wednesday at 08:00 UTC
    - cron: '0 8 * * 3'
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 60
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "⚠️ Error in requirements.txt"

      - name: Start headless display
        uses: pyvista/setup-headless-display-action@v3

      - name: Run the scraper (live logs)
        run: |
          echo "::group::Run scraper"
          stdbuf -oL -eL python -u scripts/teams_stats_other.py
          echo "::endgroup::"

      - name: Commit and Push the generated CSV file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update teams_stats_other.csv"
          branch: main
          file_pattern: ./data/teams_stats_other.csv
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
